from pathlib import Path
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from cubkit.builder import build_project, check_project
from cubkit.cli import main


class CubKitTest(unittest.TestCase):
    def test_init_check_build(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp) / "demo_mod"
            self.assertEqual(main(["init", str(project)]), 0)
            self.assertEqual(check_project(project), 2)

            output = build_project(project)
            self.assertTrue(output.is_file())
            text = output.read_text(encoding="utf-8")
            self.assertIn("Generated by CubKit", text)
            self.assertIn("def cubkit_demo()", text)


if __name__ == "__main__":
    unittest.main()
