from pathlib import Path
import contextlib
import io
import importlib.util
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from cubkit.builder import build_project, check_project
from cubkit.cli import main


class CubKitTest(unittest.TestCase):
    def test_init_check_build(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp) / "demo_mod"
            self.assertEqual(main(["init", str(project)]), 0)
            self.assertEqual(check_project(project), 2)

            output = build_project(project)
            self.assertTrue(output.is_file())
            text = output.read_text(encoding="utf-8")
            self.assertTrue(text.startswith("# name: demo_mod\n# version: 0.1.0\n"))
            self.assertIn("# description: Built with CubKit", text)
            self.assertIn("Generated by CubKit", text)
            self.assertIn("def cubkit_demo()", text)

    def test_cli_build_prints_progress(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp) / "progress_mod"
            self.assertEqual(main(["init", str(project)]), 0)

            stdout = io.StringIO()
            with contextlib.redirect_stdout(stdout):
                self.assertEqual(main(["build", str(project)]), 0)

            output = stdout.getvalue()
            self.assertIn("OK main.py", output)
            self.assertIn("OK progress_mod_lib/__init__.py", output)
            self.assertIn("OK progress_mod_lib/utils.py", output)
            self.assertIn("/3", output)
            self.assertIn("built:", output)

    def test_build_adds_manifest_metadata_header(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp) / "meta_mod"
            project.mkdir()
            (project / "cubkit.toml").write_text(
                "\n".join(
                    [
                        'id = "meta_mod"',
                        'name = "MetaModule"',
                        'version = "1.2.3"',
                        'author = "@tester"',
                        'description = "Metadata demo"',
                        'requires = ["requests", "Pillow"]',
                        'banner_url = "https://example.invalid/banner.png"',
                        'scop = "kernel min v1.3.3"',
                        'entrypoint = "main.py"',
                    ]
                ),
                encoding="utf-8",
            )
            (project / "main.py").write_text("def register(kernel):\n    pass\n", encoding="utf-8")

            text = build_project(project).read_text(encoding="utf-8")

            self.assertTrue(
                text.startswith(
                    "# name: MetaModule\n"
                    "# version: 1.2.3\n"
                    "# author: @tester\n"
                    "# description: Metadata demo\n"
                    "# requires: requests, Pillow\n"
                    "# banner_url: https://example.invalid/banner.png\n"
                    "# scop: kernel min v1.3.3\n"
                )
            )

    def test_build_uses_class_style_name_for_metadata_header(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp) / "class_mod"
            project.mkdir()
            (project / "cubkit.toml").write_text(
                "\n".join(
                    [
                        'id = "class_mod"',
                        'name = "ManifestName"',
                        'version = "1.0.0"',
                        'entrypoint = "main.py"',
                    ]
                ),
                encoding="utf-8",
            )
            (project / "main.py").write_text(
                "\n".join(
                    [
                        "from lib.utils import cmd_echo",
                        "",
                        "import core.lib.loader.module_base as loader",
                        "import core.lib.loader.module_config as cfg",
                        "",
                        "",
                        "class MyModules(loader.ModuleBase):",
                        "    name = 'MYmodule'",
                        "",
                        '    @loader.command("print")',
                        "    async def cmd(self, message) -> None:",
                        "        await self.cmd_echo(message)",
                    ]
                ),
                encoding="utf-8",
            )

            output = build_project(project)
            text = output.read_text(encoding="utf-8")

            self.assertEqual(output.name, "MYmodule.py")
            self.assertTrue(text.startswith("# name: MYmodule\n# version: 1.0.0\n"))
            self.assertNotIn("# name: ManifestName", text)
            self.assertIn("class MyModules(loader.ModuleBase):", text)

    def test_build_uses_manifest_name_for_class_style_without_name_attr(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp) / "class_mod_without_name"
            project.mkdir()
            (project / "cubkit.toml").write_text(
                "\n".join(
                    [
                        'id = "class_mod_without_name"',
                        'name = "ManifestName"',
                        'version = "1.0.0"',
                        'entrypoint = "main.py"',
                    ]
                ),
                encoding="utf-8",
            )
            (project / "main.py").write_text(
                "\n".join(
                    [
                        "import core.lib.loader.module_base as loader",
                        "",
                        "class MyModules(loader.ModuleBase):",
                        "    pass",
                    ]
                ),
                encoding="utf-8",
            )

            output = build_project(project)
            text = output.read_text(encoding="utf-8")

            self.assertEqual(output.name, "class_mod_without_name.py")
            self.assertTrue(text.startswith("# name: ManifestName\n# version: 1.0.0\n"))

    def test_entrypoint_can_use_private_relative_imports(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp) / "relative_mod"
            project.mkdir()
            (project / "cubkit.toml").write_text(
                "\n".join(
                    [
                        'id = "relative_mod"',
                        'name = "RelativeMod"',
                        'version = "1.0.0"',
                        'entrypoint = "core.py"',
                    ]
                ),
                encoding="utf-8",
            )
            (project / "utils.py").write_text(
                "def helper():\n    return 'private-relative-ok'\n",
                encoding="utf-8",
            )
            (project / "core.py").write_text(
                "from .utils import helper\n\nVALUE = helper()\n",
                encoding="utf-8",
            )

            output = build_project(project)
            spec = importlib.util.spec_from_file_location("RelativeMod", output)
            self.assertIsNotNone(spec)
            self.assertIsNotNone(spec.loader)
            module = importlib.util.module_from_spec(spec)
            sys.modules["RelativeMod"] = module
            try:
                spec.loader.exec_module(module)
                self.assertEqual(module.VALUE, "private-relative-ok")
            finally:
                sys.modules.pop("RelativeMod", None)

    def test_metadata_fields_are_optional_and_version_is_free_form(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp) / "optional_meta"
            project.mkdir()
            (project / "cubkit.toml").write_text(
                "\n".join(
                    [
                        'id = "optional_meta"',
                        'version = "dev"',
                        'entrypoint = "main.py"',
                    ]
                ),
                encoding="utf-8",
            )
            (project / "main.py").write_text("VALUE = 1\n", encoding="utf-8")

            text = build_project(project).read_text(encoding="utf-8")

            self.assertTrue(text.startswith("# name: optional_meta\n# version: dev\n"))

            (project / "cubkit.toml").write_text(
                "\n".join(
                    [
                        'id = "optional_meta"',
                        'entrypoint = "main.py"',
                    ]
                ),
                encoding="utf-8",
            )
            text = build_project(project).read_text(encoding="utf-8")
            self.assertTrue(text.startswith("# name: optional_meta\n# CubKit build info:"))
            self.assertNotIn("# version:", text.split("# ---- CubKit entrypoint:", 1)[0])

    def test_future_imports_are_moved_before_bootstrap(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp) / "future_mod"
            project.mkdir()
            (project / "cubkit.toml").write_text(
                "\n".join(
                    [
                        'id = "future_mod"',
                        'entrypoint = "main.py"',
                    ]
                ),
                encoding="utf-8",
            )
            (project / "main.py").write_text(
                '"""module doc"""\n\nfrom __future__ import annotations\n\nVALUE: list[str] = []\n',
                encoding="utf-8",
            )

            output = build_project(project)
            text = output.read_text(encoding="utf-8")

            self.assertIn("# name: future_mod\n# CubKit build info:", text)
            self.assertIn("from __future__ import annotations\n# Generated by CubKit", text)
            self.assertEqual(text.count("from __future__ import annotations"), 1)
            compile(text, str(output), "exec")

    def test_entrypoint_header_version_is_preserved_without_manifest_version(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp) / "header_version_mod"
            project.mkdir()
            (project / "cubkit.toml").write_text(
                "\n".join(
                    [
                        'id = "header_version_mod"',
                        'entrypoint = "main.py"',
                    ]
                ),
                encoding="utf-8",
            )
            (project / "main.py").write_text(
                "# version: 0.8.0-main.build:1043\nVALUE = 1\n",
                encoding="utf-8",
            )

            text = build_project(project).read_text(encoding="utf-8")

            self.assertTrue(text.startswith("# name: header_version_mod\n# version: 0.8.0-main.build:1043\n"))

    def test_multiple_package_directories_are_supported(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp) / "multi_pkg_mod"
            project.mkdir()
            (project / "cubkit.toml").write_text(
                "\n".join(
                    [
                        'id = "multi_pkg_mod"',
                        'entrypoint = "main.py"',
                        'package = ["lib_one", "lib_two"]',
                    ]
                ),
                encoding="utf-8",
            )
            (project / "lib_one").mkdir()
            (project / "lib_two").mkdir()
            (project / "lib_one" / "alpha.py").write_text("VALUE_ALPHA = 'alpha'\n", encoding="utf-8")
            (project / "lib_two" / "beta.py").write_text("VALUE_BETA = 'beta'\n", encoding="utf-8")
            (project / "main.py").write_text(
                "from .alpha import VALUE_ALPHA\n"
                "from .beta import VALUE_BETA\n\n"
                "VALUE = VALUE_ALPHA + '-' + VALUE_BETA\n",
                encoding="utf-8",
            )

            output = build_project(project)
            text = output.read_text(encoding="utf-8")

            self.assertIn("__cubkit_package_dirs__ = ('lib_one', 'lib_two')", text)
            spec = importlib.util.spec_from_file_location("MultiPkgMod", output)
            self.assertIsNotNone(spec)
            self.assertIsNotNone(spec.loader)
            module = importlib.util.module_from_spec(spec)
            sys.modules["MultiPkgMod"] = module
            try:
                spec.loader.exec_module(module)
                self.assertEqual(module.VALUE, "alpha-beta")
            finally:
                sys.modules.pop("MultiPkgMod", None)

    def test_sign_adds_signature_and_source_map_comments(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp) / "signed_mod"
            project.mkdir()
            (project / "cubkit.toml").write_text(
                "\n".join(
                    [
                        'id = "signed_mod"',
                        'entrypoint = "main.py"',
                        'package = "signed_lib"',
                        'sign = true',
                    ]
                ),
                encoding="utf-8",
            )
            (project / "signed_lib").mkdir()
            (project / "signed_lib" / "helper.py").write_text("HELPER = 'ok'\n", encoding="utf-8")
            (project / "main.py").write_text("from .helper import HELPER\nVALUE = HELPER\n", encoding="utf-8")

            text = build_project(project).read_text(encoding="utf-8")

            self.assertIn("# CubKit source sha256: ", text)
            self.assertIn("# CubKit payload sha256: ", text)
            self.assertIn("# CubKit signature: ", text)
            self.assertIn("# CubKit signature algorithm: sha256(cubkit-sign-v1", text)
            self.assertIn("# CubKit source map:", text)
            self.assertIn("-> main.py:1", text)
            self.assertIn("#   - signed_lib/helper.py -> helper.py:1", text)


if __name__ == "__main__":
    unittest.main()
