"""Render single-file MCUB module artifacts."""

from __future__ import annotations

import base64
import hashlib
import textwrap

from .manifest import Manifest


def render_module(manifest: Manifest, payload: bytes) -> str:
    """Render a generated module from *manifest* and embedded *payload*."""

    entrypoint_source = manifest.entrypoint.read_text(encoding="utf-8")
    payload_hash = hashlib.sha256(payload).hexdigest()
    encoded_payload = base64.b85encode(payload).decode("ascii") if payload else ""
    bootstrap = _render_bootstrap(manifest.module_id, payload_hash, encoded_payload)
    return f"{bootstrap}\n\n# ---- CubKit entrypoint: {manifest.entrypoint.name} ----\n{entrypoint_source}\n"


def _render_bootstrap(module_id: str, payload_hash: str, encoded_payload: str) -> str:
    if not encoded_payload:
        return (
            "# Generated by CubKit. Do not edit this header by hand.\n"
            f"__cubkit_module_id__ = {module_id!r}\n"
            '__cubkit_bundle_sha256__ = ""'
        )

    wrapped_payload = "\n".join(textwrap.wrap(encoded_payload, width=100))
    return f'''# Generated by CubKit. Do not edit this header by hand.
__cubkit_module_id__ = {module_id!r}
__cubkit_bundle_sha256__ = {payload_hash!r}
__cubkit_bundle_b85__ = """
{wrapped_payload}
"""

def __cubkit_bootstrap__():
    import base64
    import hashlib
    import os
    import sys
    import zipfile
    from pathlib import Path

    data = base64.b85decode("".join(__cubkit_bundle_b85__.split()).encode("ascii"))
    digest = hashlib.sha256(data).hexdigest()
    if digest != __cubkit_bundle_sha256__:
        raise RuntimeError("CubKit embedded bundle checksum mismatch")

    cache_root = Path(os.environ.get("CUBKIT_CACHE_DIR", Path.home() / ".cache" / "cubkit"))
    bundle_dir = cache_root / __cubkit_module_id__ / digest
    marker = bundle_dir / ".cubkit-extracted"
    if not marker.exists():
        bundle_dir.mkdir(parents=True, exist_ok=True)
        archive_path = bundle_dir / "bundle.zip"
        archive_path.write_bytes(data)
        with zipfile.ZipFile(archive_path) as archive:
            archive.extractall(bundle_dir)
        marker.write_text(digest, encoding="utf-8")

    bundle_path = str(bundle_dir)
    if bundle_path not in sys.path:
        sys.path.insert(0, bundle_path)

__cubkit_bootstrap__()
del __cubkit_bootstrap__'''
